name: Coding Standard

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches-ignore:
    - 'master'

jobs:
  Check_Coding_Standard:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Run cpplint
      run: bash scripts/run_cpplint.sh
