name: Coding Standard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Check_Coding_Standard:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Installing cpplint
      run: pip install cpplint
    
    - name: Run cpplint
      run: cpplint --recursive --filter=-legal/copyright,-whitespace/indent *
