name: System Build

on: [push, pull_request] 

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Boost
      run: |
        sudo apt-get install aptitude
        sudo aptitude install libboost-all-dev -y

    - name: Installing Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        pushd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        popd

    - name: Run CMake
      run: |
        mkdir build
        cmake -Bbuild -H.

    - name: Build
      run: cmake --build build/ --target all