name: System Build

on: [push, pull_request] 

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: make