name: System Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'src/UI/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'src/UI/**'

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Boost
      run: |
        sudo apt-get install aptitude
        sudo aptitude install libboost-all-dev -y

    - name: Installing Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        pushd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        popd

    - name: Run CMake
      run: |
        mkdir build
        cmake -Bbuild -H.

    - name: Build
      run: cmake --build build/ --target all

    - name: Unit Tests
      run: |
        cd build
        make test

  Integration_Tests:

    runs-on: ubuntu-latest
    needs: [Build]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run requirements file
      run: pip install -r requirements.txt

    - name: Get branch name (merge)
      if: github.event != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Run server setup script
      run: python scripts/server_setup.py ${{ env.BRANCH_NAME }}

    - name: Run tests
      run: |
        cd tests/RequestTests
        pytest HWTrackCtrlRequestTests.py --setup-show
        pytest TrainModelRequestTests.py --setup-show
