name: Tests

on:
  repository_dispatch:
    types: [build_successful]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run requirements file
      run: pip install -r requirements.txt

    - name: Get branch name (merge)
      if: github.event.client_payload.message.original_event != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Run server setup script
      run: python scripts/server_setup.py ${{ env.BRANCH_NAME }}

    - name: Run tests
      run: pytest tests/RequestTests/HWTrackCtrlRequestTests.py --setup-show