name: Testing

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run requirements file
      run: pip install -r requirements.txt

    - name: Run CTC tests
      run: python tests/UnitTests/CTC/*.py

    - name: Run SWTrack tests
      run: |
        pushd tests/UnitTests/SWTrackController/Compiler
        pytest --setup-show
        popd

    - name: Run SWTrain tests
      run: pytest tests/UnitTests/SWTrainController/ControllerUT.py

    - name: Run TrainModel-SWTrain Tests
      run: pytest tests/IntegrationTests/test_trainmodel_swtrain.py

    - name: Run TrainModel TrackModel Tests
      run: pytest tests/IntegrationTests/test_track_train_models.py

    - name: Run Passing Occupancy Test
      run: pytest tests/IntegrationTests/test_passing_occupancy.py

    - name: Run Passing Authority Test
      run: pytest tests/IntegrationTests/test_passing_authority.py
      
    - name: Run Common tests
      run: pytest tests/IntegrationTests/test_common.py
